version: '3'
services:
    duckietown-notebook:
        build:
            context: .
            dockerfile: DockerfileNB
        depends_on:
        - "rosmaster"
        networks:
        - duckietown-docker-net
        volumes:
        - ./software/:/duckietown/software/
        - ./simulation/:/duckietown/simulation/
        expose:
        - "8888"
        ports:
        - "8888:8888"
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
        - "ROS_MASTER_URI=http://rosmaster:11311"

    rosmaster:
        image: osrf/ros:melodic-desktop-full-bionic
        networks:
        - duckietown-docker-net
        command: 
        - roscore
        environment:
        - "ROS_MASTER_URI=http://rosmaster:11311"

networks:
    duckietown-docker-net:


        